### PR TITLE
Fix to compile with Qt5.2.1 on Ubuntu 14.04.

### PR DESCRIPTION
**Pull request by ashwin**
Fixes this compile error with Qt 5.2.1 (which is the Qt version available on Ubuntu 14.04 LTS):

```
In file included from /home/joe/glCapsViewer/glCapsViewer.h:28:0,
                 from /home/joe/glCapsViewer/glCapsViewer.cpp:23:
/home/joe/glCapsViewer/GeneratedFiles/ui_glcapsviewer.h: In member function ‘void Ui_glcapsviewerClass::setupUi(QMainWindow*)’:
/home/joe/glCapsViewer/GeneratedFiles/ui_glcapsviewer.h:154:20: error: ‘class QTabWidget’ has no member named ‘setTabBarAutoHide’
         tabWidget->setTabBarAutoHide(false);
                    ^
```

### CODE REVIEW

**Comment by SaschaWillems** [comment]
Thanks for this fix, Looks like this property was introduced with Qt 5.4 and is set to false by default, so removing it should be fine.
